import gulp from 'gulp';
import cleanCSS from 'gulp-clean-css';
import htmlmin from 'gulp-htmlmin';
import concat from 'gulp-concat';
import sourcemaps from 'gulp-sourcemaps';
import gulpif from 'gulp-if';
import rename from 'gulp-rename';
import { deleteAsync } from 'del';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import replace from 'gulp-replace';
import jsonMinify from 'gulp-json-minify';
import crypto from 'crypto';
import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import rollupTerser from '@rollup/plugin-terser';
import fs from 'fs/promises';
import path from 'path';
import { glob } from 'glob';

// Get command line arguments
const argv = yargs(hideBin(process.argv)).argv;
const isProduction = argv.production || process.env.NODE_ENV === 'production';

// Paths configuration
const paths = {
  src: {
    js: {
      entry: 'js/main.js',
      all: 'js/**/*.js'
    },
    html: {
      main: 'index.html'
    },
    lang: 'js/translations.js'
  },
  dist: 'dist',
  temp: '.tmp'
};

// Clean task
function clean() {
  return deleteAsync([paths.dist, paths.temp]);
}

// JavaScript bundling with Rollup
async function scripts() {
  const inputOptions = {
    input: paths.src.js.entry,
    plugins: [
      nodeResolve(),
      ...(isProduction ? [
        rollupTerser({
          compress: {
            drop_console: false,
            drop_debugger: true,
            pure_funcs: ['console.debug', 'console.trace'],
            passes: 2,
            unsafe: true,
            unsafe_comps: true,
            unsafe_math: true,
            unsafe_proto: true
          },
          mangle: {
            reserved: [
              'gboot', 'connect', 'disconnect', 'disconnectSync',
              'show_faq_modal', 'calibrate_stick_centers', 'calibrate_range',
              'ds5_finetune', 'auto_calibrate_stick_centers', 'flash_all_changes',
              'reboot_controller', 'welcome_accepted', 'show_info_tab',
              'nvslock', 'nvsunlock', 'refresh_nvstatus', 'show_edge_modal',
              'show_donate_modal'
            ],
            properties: {
              regex: /^_/
            }
          },
          format: {
            comments: false
          }
        })
      ] : [])
    ]
  };

  let filename = 'app.js';

  if (isProduction) {
    const bundle = await rollup(inputOptions);
    const { output } = await bundle.generate({ format: 'es' });
    const code = output[0].code;
    const hash = crypto.createHash('md5').update(code).digest('hex').substring(0, 8);
    filename = `app-${hash}.js`;

    // Ensure dist directory exists
    await fs.mkdir(paths.dist, { recursive: true });
    await fs.writeFile(path.join(paths.dist, filename), code);
    await bundle.close();
  } else {
    // Ensure dist directory exists
    await fs.mkdir(paths.dist, { recursive: true });
    const outputOptions = {
      file: path.join(paths.dist, filename),
      format: 'es',
      sourcemap: true
    };

    const bundle = await rollup(inputOptions);
    await bundle.write(outputOptions);
    await bundle.close();
  }

  // Store the filename for HTML processing
  global.jsFilename = filename;
  return Promise.resolve();
}

// HTML processing
async function html() {
  const jsFile = global.jsFilename || 'app.js';

  let htmlContent = await fs.readFile(paths.src.html.main, 'utf8');

  // Replace script reference
  htmlContent = htmlContent.replace('<script type="module" src="js/main.js"></script>', `<script type="module" src="${jsFile}"></script>`);

  // In production, minify HTML
  if (isProduction) {
    const htmlMinify = (await import('html-minifier-terser')).minify;
    htmlContent = await htmlMinify(htmlContent, {
      caseSensitive: false,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      decodeEntities: true,
      html5: true,
      includeAutoGeneratedTags: true,
      keepClosingSlash: false,
      minifyCSS: true,
      minifyJS: true,
      minifyURLs: false,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: false,
      removeAttributeQuotes: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeEmptyElements: false,
      removeOptionalTags: true,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace: false,
      sortAttributes: true,
      sortClassName: true,
      trimCustomFragments: true,
      useShortDoctype: true
    });
  }

  // Write the processed HTML file
  await fs.writeFile(path.join(paths.dist, 'index.html'), htmlContent);
  return Promise.resolve();
}

// Language files processing
async function languages() {
  // For now, we're treating translations.js as a JS module, so it gets bundled with scripts
  // This function is kept for compatibility with the existing task structure
  return Promise.resolve();
}

// Copy assets (none specific for now, but keeping for compatibility)
function assets() {
  return Promise.resolve();
}

// Watch task
function watch() {
  gulp.watch(paths.src.js.all, scripts);
  gulp.watch(paths.src.html.main, html);
  // In a real implementation, we'd also watch for language files, etc.
}

// Development task
function dev() {
  console.log('🚀 Development mode - watching files for changes...');
  return watch();
}

// Build task
const build = gulp.series(
  clean,
  gulp.parallel(scripts),
  gulp.parallel(html, languages, assets)
);

// Export tasks
export { clean, scripts, html, languages, assets, watch, dev, build };
export default build;